function memeories()
close all;
figure('Name','Math(Work)s','NumberTitle','off','Resize','off');
uicontrol('Style', 'text', 'FontSize', 30, 'String', 'MEMEories',...
    'Position', [30 320 500 50], 'FontName', 'comic sans ms');

uicontrol('Style', 'pushbutton', 'FontSize', 18, 'String', 'Browse Old Memes',...
    'Position', [30 210 500 80],...
    'Callback', @redditbrowser, 'FontName', 'comic sans ms');

uicontrol('Style', 'pushbutton', 'FontSize', 18, 'String', 'Create New Memes',...
    'Position', [30 110 500 80],...
    'Callback', @mememaker, 'FontName', 'comic sans ms');

uicontrol('Style', 'text', 'String', 'by Alex, Alexa, Jon, and William',...
    'Position', [350 10 200 20], 'FontName', 'comic sans ms');
end